 # Copyright (c) 2022, salesforce.com, inc.
 # All rights reserved.
 # SPDX-License-Identifier: BSD-3-Clause
 # For full license text, see the LICENSE file in the repo root or https://opensource.org/licenses/BSD-3-Clause

datasets:
  coco_vqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images # [images|videos|features]

    build_info:

      annotations:
        train:
          url:
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/vqa_train.json
              - https://storage.googleapis.com/sfr-vision-language-research/LAVIS/datasets/vqav2/vqa_val.json
          storage:
              - /home/users/nus/idmwyk/scratch/temp/dataset/vqav2/vqa_train.json
              - /home/users/nus/idmwyk/scratch/temp/dataset/vqav2/vqa_val.json
      images:
          storage: /home/users/nus/idmwyk/scratch/temp/dataset/coco/images

  