datasets:
  invrefcocop:
    data_type: images
    build_info:
      image_path: /home/users/nus/idmwyk/scratch/temp/dataset/coco/images
      ann_path: /home/users/nus/idmwyk/scratch/temp/dataset/refcoco_annotations
      dataset: invrefcoco+
      splitBy: unc