model:
  arch: minigpt_v4
  model_type: pretrain
  max_txt_len: 1024
  image_size: 448
  end_sym: "</s>"
  llama_model: "/home/users/nus/idmwyk/scratch/temp/checkpoint/Meta-Llama-3.1-8B-Instruct" # change your llama model path
  ckpt: # "/path/to/pretrained_checkpoint"
  use_grad_checkpoint: True
  chat_template: True
  lora_r: 64
  lora_alpha: 16

datasets:
  laion: # checked
    batch_size: 4 # change from 64 to 4 to avoid OOD
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 115

  cc_sbu: # checked
    batch_size: 4 # change from 64 to 4 to avoid OOD
    vis_processor:
        train:
          name: "blip2_image_train"
          image_size: 448
    text_processor:
        train:
          name: "blip_caption"
    sample_ratio: 14

  refvg: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 40

  coco_caption: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10  
 
  textcaps_caption:  # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30

  refcoco: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 25

  refcocop: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 25

  refcocog: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 25

  invrefcoco: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

  invrefcocop: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

  invrefcocog: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 10

  coco_vqa: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 15

  ok_vqa:  # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 8

  aok_vqa: # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 12

  gqa:  # checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 50

  ocrvqa: #  checked
    batch_size: 4
    vis_processor:
      train:
        name: "blip2_image_train"
        image_size: 448
    text_processor:
      train:
        name: "blip_caption"
    sample_ratio: 30


run:
  task: image_text_pretrain
  # optimizer
  lr_sched: "linear_warmup_cosine_lr"
  init_lr: 1e-5
  min_lr: 1e-6
  warmup_lr: 1e-6

  weight_decay: 0.05
  max_epoch: 50
  num_workers: 32  # zy change from 6 to 32 to speed up data loading
  warmup_steps: 1000
  iters_per_epoch: 1000

  seed: 42
  output_dir: "/home/users/nus/idmwyk/scratch/temp/output/saved-ckpt/minigptv4/stage1" #"/path/to/save_checkpoint"

  amp: True
  resume_ckpt_path: null

  evaluate: False 
  train_splits: ["train"]

  device: "cuda"
  world_size: 1
  dist_url: "env://"
  distributed: True

  wandb_log: True # change
  job_name: minigptv4_llama3_stage1_pretrain
