datasets:
  textcaps_caption:
    data_type: images
    
    build_info:
      image_path: /home/users/nus/idmwyk/scratch/temp/dataset/textcaps/train_images
      ann_path: /home/users/nus/idmwyk/scratch/temp/dataset/textcaps/TextCaps_0.1_train.json


